version: "3.8"

services:
  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - 3000:3000

  backend:
    restart: unless-stopped
    depends_on:
      - datamiola
    build: ./backend
    ports:
      - 9090:8080
    env_file:
    - ./backend/.env
    

  datamiola:
    build: ./backend/docker
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE=miola
      - MYSQL_ROOT_PASSWORD=root
      
    